id: agent-orchestrator-script
namespace: default
tasks:
  - id: orchestrate
    type: io.kestra.plugin.scripts.node.Script
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    script: |-
      (async () => {
        try {
          const token = '{{ secret("GITHUB_TOKEN") }}';
          if (!token) { console.log('NO_TOKEN_AVAILABLE'); return; }

          const headers = { Authorization: 'token ' + token, 'User-Agent': 'kestra' };

          // Fetch repo data for decision-making
          const repoRes = await fetch('https://api.github.com/repos/something1703/r2d2-agent', { headers });
          if (!repoRes.ok) { console.error('REPO_FETCH_ERROR', repoRes.status); return; }
          const repoData = await repoRes.json();

          // Fetch issues
          const issuesRes = await fetch('https://api.github.com/repos/something1703/r2d2-agent/issues', { headers });
          if (!issuesRes.ok) { console.error('ISSUES_FETCH_ERROR', issuesRes.status); return; }
          const issues = await issuesRes.json();

          // AI AGENT DECISION LOGIC
          const issuesCount = Array.isArray(issues) ? issues.length : 0;
          const openIssuesCount = repoData.open_issues_count || 0;
          const lastUpdated = new Date(repoData.updated_at);
          const daysSinceUpdate = (Date.now() - lastUpdated) / (1000 * 60 * 60 * 24);

          let decision = { action: 'none', reason: 'No action needed' };

          // Decision logic
          if (openIssuesCount > 5) {
            decision = { action: 'fix-issues', reason: `Found ${openIssuesCount} open issues - triggering auto-fix` };
          } else if (daysSinceUpdate > 7) {
            decision = { action: 'update-docs', reason: 'Repo not updated in 7 days - updating documentation' };
          } else if (issuesCount > 0 && issuesCount <= 5) {
            decision = { action: 'code-review', reason: 'Running code quality review' };
          }

          const summary = {
            repo: 'something1703/r2d2-agent',
            count: issuesCount,
            titles: Array.isArray(issues) ? issues.slice(0,5).map(i=>i.title) : [],
            decision: decision,
            metrics: {
              openIssues: openIssuesCount,
              daysSinceUpdate: Math.round(daysSinceUpdate),
              stars: repoData.stargazers_count || 0
            }
          };

          console.log('SUMMARY:', JSON.stringify(summary));
          console.log('DECISION:', JSON.stringify(decision));

          // Post summary to Next.js API
          await fetch('http://host.docker.internal:3000/api/kestra-summary', {
            method: 'POST',
            headers: {'Content-Type':'application/json'},
            body: JSON.stringify(summary)
          });

          console.log('POSTED_SUMMARY');
        } catch (e) {
          console.error('SCRIPT_ERROR', e && e.stack ? e.stack : e);
          process.exit(1);
        }
      })();

