#!/usr/bin/env bash
# R2D2 Agent - Cline CLI Automation Script
# This script is triggered by the /api/run-agent endpoint

set -e

echo "=========================================="
echo "🤖 R2D2 Cline Automation Started"
echo "=========================================="
echo "Timestamp: $(date)"
echo "Action: ${ACTION:-default}"
echo "------------------------------------------"

# Get action from environment variable (set by API)
ACTION="${ACTION:-default}"
PARAMS="${PARAMS:-{}}"

# Parse the repo owner and name from environment or use defaults
REPO_OWNER="${REPO_OWNER:-something1703}"
REPO_NAME="${REPO_NAME:-r2d2-agent}"

case "$ACTION" in
  "trigger-kestra")
    echo "📡 Triggering Kestra flow..."
    curl -sS -u "${KES_USER:-rudra@example.com}:${KES_PASS:-Kestra123}" \
      -X POST "http://127.0.0.1:8080/api/v1/main/executions/default/agent-orchestrator-script" \
      -F "execution={}" -F "inputs={}" | jq .
    ;;
    
  "create-pr")
    echo "🔀 Creating automated PR..."
    
    # Check if we have uncommitted changes
    if git diff-index --quiet HEAD --; then
      echo "📝 No changes detected, creating sample improvement..."
      echo "# Code Quality Improvements" >> IMPROVEMENTS.md
      echo "- Automated code review completed" >> IMPROVEMENTS.md
      echo "- Generated on $(date)" >> IMPROVEMENTS.md
      git add IMPROVEMENTS.md
      git commit -m "🤖 Automated improvements by Cline CLI"
    fi
    
    # Create a new branch and push
    BRANCH="cline-improvements-$(date +%s)"
    git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"
    git push origin "$BRANCH" 2>/dev/null || echo "Branch already pushed"
    
    echo "✅ Branch $BRANCH ready for PR creation"
    echo "💡 Use: gh pr create --title '🤖 Automated Improvements' --body 'Generated by Cline CLI'"
    ;;
    
  "fix-issues")
    echo "🔧 Analyzing and fixing issues..."
    
    # Fetch open issues from GitHub
    echo "📥 Fetching open issues from ${REPO_OWNER}/${REPO_NAME}..."
    ISSUES=$(curl -s "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/issues?state=open&per_page=5")
    
    ISSUE_COUNT=$(echo "$ISSUES" | jq '. | length')
    echo "📊 Found $ISSUE_COUNT open issues"
    
    if [ "$ISSUE_COUNT" -gt 0 ]; then
      echo "🤖 Cline CLI would analyze and fix these issues"
      echo "$ISSUES" | jq -r '.[] | "  - #\(.number): \(.title)"'
      
      # Simulate Cline CLI automation
      echo "✅ Issues analyzed (Cline CLI automation ready for implementation)"
    else
      echo "✅ No open issues to fix"
    fi
    ;;
    
  "update-docs")
    echo "📚 Updating documentation..."
    
    # Analyze codebase structure
    echo "🔍 Analyzing codebase..."
    FILE_COUNT=$(find app -type f -name '*.tsx' -o -name '*.ts' | wc -l)
    API_COUNT=$(find app/api -type f -name 'route.ts' 2>/dev/null | wc -l)
    
    echo "📊 Project stats:"
    echo "  - TypeScript/TSX files: $FILE_COUNT"
    echo "  - API routes: $API_COUNT"
    
    # Generate documentation update
    cat >> CLINE_DOCS.md << EOF

## Project Structure (Updated $(date))

- Total files: $FILE_COUNT
- API endpoints: $API_COUNT
- Auto-generated by Cline CLI

EOF
    
    echo "✅ Documentation analysis complete"
    echo "📝 See CLINE_DOCS.md for generated documentation"
    ;;
    
  "code-review")
    echo "👁️  Running automated code review..."
    
    # Analyze recent commits
    echo "📜 Analyzing recent commits..."
    RECENT_COMMITS=$(git log --oneline -5)
    echo "$RECENT_COMMITS"
    
    # Check for common code quality issues
    echo ""
    echo "🔍 Code quality checks:"
    
    # Check for TODO comments
    TODO_COUNT=$(grep -r "TODO" app scripts --include="*.ts" --include="*.tsx" --include="*.sh" 2>/dev/null | wc -l)
    echo "  - TODO comments found: $TODO_COUNT"
    
    # Check for console.log statements
    CONSOLE_COUNT=$(grep -r "console.log" app --include="*.ts" --include="*.tsx" 2>/dev/null | wc -l)
    echo "  - console.log statements: $CONSOLE_COUNT"
    
    # Generate review summary
    echo ""
    echo "📋 Review Summary:"
    if [ $TODO_COUNT -gt 0 ]; then
      echo "  ⚠️  Consider addressing $TODO_COUNT TODO items"
    fi
    if [ $CONSOLE_COUNT -gt 10 ]; then
      echo "  💡 Consider using a logger instead of console.log"
    fi
    
    echo "✅ Code review completed"
    ;;
    
  "default"|*)
    echo "🔄 Running default action: No action (preventing infinite loop)"
    echo "✅ Summary received and logged. No further action needed."
    ;;
esac

echo "------------------------------------------"
echo "✅ Automation completed successfully"
echo "=========================================="

exit 0

